// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://madeprjbbnaanhhsxxav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZGVwcmpiYm5hYW5oaHN4eGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDY2NzEsImV4cCI6MjA2ODQyMjY3MX0.Sh1jsKrynyv05__gRAF-lPZlsDhBGx9JhH1wmM8eQLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);